const departments=['Ban quản trị','Kế toán','Sản xuất','Thi công'];
const str=(v,n)=>String(v??'').trim().slice(0,n);
function date(v){if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)throw Error('Ngày không hợp lệ');return v;}
module.exports=(app,{pool,auth,ceo})=>{
const board=(r,s,n)=>r.session.user?.department==='Ban quản trị'?n():s.status(403).json({error:'Chỉ thành viên Ban quản trị được điều hành.'});
app.get('/api/edit/people',auth,board,async(r,s)=>s.json((await pool.query("SELECT name,department FROM users WHERE active=true UNION SELECT name,department FROM employees WHERE active=true AND is_seed=false ORDER BY department,name")).rows));
for(const entity of ['tasks','projects']){
app.patch('/api/edit/'+entity+'/:id',auth,board,async(r,s)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM '+entity+' WHERE id=$1 FOR UPDATE',[r.params.id])).rows[0];if(!old)throw Error('Không tìm thấy dữ liệu.');if(r.body.version!==JSON.stringify(old))throw Error('Dữ liệu đã thay đổi. Đóng cửa sổ, làm mới và mở lại.');const b=r.body;const name=str(b.name,300),notes=str(b.notes,10000),person=str(b.person,200),start=date(b.start),due=date(b.due);if(!name)throw Error('Nhập tên/nội dung.');if(start&&due&&start>due)throw Error('Ngày hoàn thành phải sau ngày bắt đầu.');
if(person&&person!=='Chưa phân công'){const found=(await c.query('SELECT name,department FROM users WHERE active=true AND name=$1 UNION SELECT name,department FROM employees WHERE active=true AND is_seed=false AND name=$1',[person])).rows;if(!found.length||entity==='tasks'&&!found.some(x=>x.department===b.department))throw Error('Chọn nhân sự đang hoạt động đúng phòng ban.');}
if(entity==='tasks'){if(!departments.includes(b.department))throw Error('Phòng ban không hợp lệ.');const statuses=['Chờ triển khai','Đang sản xuất','Chờ thi công','Đang thi công','Nghiệm thu','Hoàn thành'];if(!statuses.includes(b.status))throw Error('Trạng thái không hợp lệ.');const progress=Math.max(0,Math.min(100,Number(b.progress)||0));await c.query('UPDATE tasks SET title=$1,department=$2,assignee=$3,notes=$4,start_date=$5,due_date=$6,status=$7,progress=$8,updated_at=now() WHERE id=$9',[name,b.department,person||'Chưa phân công',notes,start,due,b.status,progress,old.id]);}else{await c.query('UPDATE projects SET name=$1,client=$2,manager=$3,edit_notes=$4,start_date=$5,due_date=$6 WHERE id=$7',[name,str(b.client,300),person,notes,start,due,old.id]);}
await c.query('INSERT INTO audit_logs(user_id,action,entity,entity_id,note) VALUES($1,$2,$3,$4,$5)',[r.session.user.id,'Sửa thông tin và phân công',entity,String(old.id),JSON.stringify({before:old,after:{name,person,notes,start,due,department:b.department,client:b.client}})]);await c.query('COMMIT');s.json({ok:true});}catch(e){await c.query('ROLLBACK');s.status(400).json({error:e.message});}finally{c.release();}});
app.get('/api/edit/'+entity+'/:id',auth,board,async(r,s)=>{const q=(await pool.query('SELECT * FROM '+entity+' WHERE id=$1',[r.params.id])).rows[0];if(!q)return s.status(404).json({error:'Không có dữ liệu.'});s.json({row:q,version:JSON.stringify(q)});});
// Hard deletion only for empty records. Check every referencing FK including CASCADE.
app.post('/api/edit/'+entity+'/:id/delete',auth,ceo,async(r,s)=>{if(r.body.confirmed!==true)return s.status(400).json({error:'Cần xác nhận xóa.'});const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM '+entity+' WHERE id=$1 FOR UPDATE',[r.params.id])).rows[0];if(!old)throw Error('Không có dữ liệu.');if(r.body.version!==JSON.stringify(old))throw Error('Dữ liệu đã thay đổi. Mở lại trước khi xóa.');
const refs=(await c.query(`SELECT ns.nspname schema_name,cl.relname table_name,a.attname column_name FROM pg_constraint co JOIN pg_class cl ON cl.oid=co.conrelid JOIN pg_namespace ns ON ns.oid=cl.relnamespace JOIN pg_attribute a ON a.attrelid=co.conrelid AND a.attnum=co.conkey[1] WHERE co.contype='f' AND co.confrelid=$1::regclass`,[entity])).rows;
const quote=x=>'"'+x.replace(/"/g,'""')+'"';for(const ref of refs){if(entity==='projects'&&ref.table_name==='project_folders')continue;if((await c.query('SELECT 1 FROM '+quote(ref.schema_name)+'.'+quote(ref.table_name)+' WHERE '+quote(ref.column_name)+'=$1 LIMIT 1',[old.id])).rows.length)throw Error('Dữ liệu đã có hồ sơ/công việc/chứng từ liên quan nên không xóa. Hãy chỉnh sửa để giữ lịch sử.');}
if(entity==='projects'){if((await c.query('SELECT 1 FROM project_documents d JOIN project_folders f ON f.id=d.folder_id WHERE f.project_id=$1 LIMIT 1',[old.id])).rows.length)throw Error('Thư mục dự án còn hồ sơ, không xóa.');await c.query('DELETE FROM project_folders WHERE project_id=$1',[old.id]);}
await c.query('DELETE FROM '+entity+' WHERE id=$1',[old.id]);await c.query('INSERT INTO audit_logs(user_id,action,entity,entity_id,note) VALUES($1,$2,$3,$4,$5)',[r.session.user.id,'Xóa bản ghi trống',entity,String(old.id),JSON.stringify(old)]);await c.query('COMMIT');s.json({ok:true});}catch(e){await c.query('ROLLBACK');s.status(400).json({error:e.message});}finally{c.release();}});
}
return ()=>pool.query("ALTER TABLE projects ADD COLUMN IF NOT EXISTS edit_notes TEXT NOT NULL DEFAULT ''");
};
