const {zipSync,strToU8}=require('fflate');
const esc=v=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
const cell=v=>typeof v==='number'&&Number.isFinite(v)?`<c><v>${v}</v></c>`:`<c t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;
function sheet(rows){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>${rows.map((r,i)=>`<row r="${i+1}">${r.map(cell).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col(rows.reduce((n,r)=>Math.max(n,r.length),1))}${rows.length||1}"/></worksheet>`;}
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function rows(headers,data,fields){return [headers,...data.map(x=>fields.map(f=>{const v=typeof f==='function'?f(x):x[f];return v instanceof Date?v.toISOString().slice(0,10):v??'';}))];}
function workbook(tabs){const files={};files['[Content_Types].xml']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${tabs.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>`);files['_rels/.rels']=strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>');files['xl/workbook.xml']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${tabs.map((t,i)=>`<sheet name="${esc(t.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);files['xl/_rels/workbook.xml.rels']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${tabs.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`);files['docProps/core.xml']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"><dc:title>Mái Nhà Đẹp OS - Báo cáo dự án</dc:title><dc:creator>Mái Nhà Đẹp OS</dc:creator><dcterms:created>${new Date().toISOString()}</dcterms:created></cp:coreProperties>`);tabs.forEach((t,i)=>files[`xl/worksheets/sheet${i+1}.xml`]=strToU8(sheet(t.rows)));return Buffer.from(zipSync(files,{level:6}));}
module.exports=(app,{pool,auth,ceo})=>{
 ceo=(r,s,n)=>r.session.user?.department==='Ban quản trị'?n():s.status(403).json({error:'Chỉ thành viên Ban quản trị được xuất toàn bộ dự án.'});
 app.get('/api/export/project/:id.xlsx',auth,ceo,async(r,s)=>{try{const id=Number(r.params.id);if(!Number.isInteger(id)||id<1)throw Error('Dự án không hợp lệ.');const project=(await pool.query('SELECT * FROM projects WHERE id=$1',[id])).rows[0];if(!project)return s.status(404).json({error:'Không có dự án.'});const q=await Promise.all([
  pool.query('SELECT * FROM tasks WHERE project_id=$1 ORDER BY id',[id]),pool.query('SELECT * FROM sc_items WHERE project_id=$1 ORDER BY id',[id]),pool.query('SELECT p.*,i.code item_code,c.name crew_name FROM sc_packages p JOIN sc_items i ON i.id=p.item_id JOIN sc_crews c ON c.id=p.crew_id WHERE i.project_id=$1 ORDER BY p.id',[id]),pool.query('SELECT r.*,p.code package_code FROM sc_reports r JOIN sc_packages p ON p.id=r.package_id JOIN sc_items i ON i.id=p.item_id WHERE i.project_id=$1 ORDER BY r.report_date,r.id',[id]),pool.query('SELECT a.*,i.code item_code,p.code package_code FROM sc_acceptances a JOIN sc_items i ON i.id=a.item_id LEFT JOIN sc_packages p ON p.id=a.package_id WHERE a.project_id=$1 ORDER BY a.event_date,a.id',[id]),pool.query('SELECT * FROM transactions WHERE project_id=$1 ORDER BY tx_date,id',[id]),pool.query('SELECT d.*,f.folder_order,f.name folder_name FROM project_documents d LEFT JOIN project_folders f ON f.id=d.folder_id WHERE d.project_id=$1 ORDER BY f.folder_order,d.id',[id])]);const [tasks,items,packs,reports,acc,tx,docs]=q.map(x=>x.rows);
  const tabs=[
   {name:'01-Du-an',rows:rows(['Mã','Tên dự án','Khách hàng','Trạng thái','Bắt đầu','Hoàn thành','Giá trị hợp đồng','Ngân sách','Quản lý'],[project],['code','name','client','status','start_date','due_date',x=>Number(x.contract_value||0),x=>Number(x.approved_budget||0),'manager'])},
   {name:'02-Cong-viec',rows:rows(['ID','Nội dung','Phòng ban','Người phụ trách','Trạng thái','Ưu tiên','Tiến độ %','Bắt đầu','Hạn chót','KL kế hoạch','KL thực tế','ĐVT','ID phụ thuộc','Ghi chú'],tasks,['id','title','department','assignee','status','priority',x=>Number(x.progress||0),'start_date','due_date',x=>Number(x.planned_qty||0),x=>Number(x.actual_qty||0),'quantity_unit','dependency_id','notes'])},
   {name:'03-Hang-muc',rows:rows(['ID','Mã','Hạng mục','ĐVT','KL nhận thầu','Đơn giá nhận thầu','Giá trị'],items,['id','code','name','unit',x=>Number(x.qty),x=>Number(x.sale_price),x=>Number(x.qty)*Number(x.sale_price)])},
   {name:'04-Goi-khoan',rows:rows(['ID','Mã gói','Hạng mục','Tên gói','Tổ đội','Hình thức','Khối lượng','Đơn giá khoán','Giá trị','Bắt đầu','Hoàn thành','Tạm ứng dự kiến','Giữ lại %','Trạng thái'],packs,['id','code','item_code','name','crew_name','kind',x=>Number(x.qty),x=>Number(x.unit_price),x=>Number(x.qty)*Number(x.unit_price),'start_date','due_date',x=>Number(x.advance_plan||0),x=>Number(x.retention_percent||0),'status'])},
   {name:'05-Bao-cao',rows:rows(['ID','Mã gói','Mã báo cáo','Ngày','Khối lượng trong ngày','Nhân lực','Nội dung','Người tạo'],reports,['id','package_code','report_key','report_date',x=>Number(x.qty),x=>Number(x.workers),'note','created_by'])},
   {name:'06-Nghiem-thu',rows:rows(['ID','Phía','Biên bản','Ngày','Hạng mục','Gói','Khối lượng','Đơn giá','Giá trị','Ghi chú'],acc,['id','side','document_no','event_date','item_code','package_code',x=>Number(x.qty),x=>Number(x.unit_price),x=>Number(x.qty)*Number(x.unit_price),'note'])},
   {name:'07-Thu-Chi',rows:rows(['ID','Ngày','Thu/Chi','Nhóm','Số tiền','Chứng từ','Nội dung'],tx,['id','tx_date','type','category',x=>Number(x.amount),'document_no','description'])},
   {name:'08-Ho-so',rows:rows(['ID','Nhóm số','Nhóm hồ sơ','Tên tài liệu','Trạng thái','Phiên bản','Cập nhật'],docs,['id','folder_order','folder_name','title','status','current_revision','updated_at'])}
  ];const file=workbook(tabs),name=String(project.code||'du-an').replace(/[^a-zA-Z0-9_-]+/g,'-');s.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');s.setHeader('Content-Disposition',`attachment; filename="MND-${name}.xlsx"`);s.setHeader('Content-Length',file.length);s.send(file);
 }catch(e){s.status(400).json({error:e.message});}});
 return()=>Promise.resolve();
};
module.exports.workbook=workbook;
